WcfAspNetCoreService/AspNetCoreProject/Controllers/PrimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PrimeServiceReference;

namespace AspNetCoreProject.Controllers
{
    [Route("controller")]
    public class PrimeController : Controller
    {
        private PrimesServiceClient  primeServiceClient = new PrimesServiceClient();

        [Route("~/")]
        public IActionResult Index(int PrimeIndex)
        {
            
            PrimeServiceReference.Primes pr = new PrimeServiceReference.Primes();
            if (PrimeIndex > 0)
            {
                pr.Index = PrimeIndex;
                pr.PrimeNumber = primeServiceClient.GetPrimeByIndexAsync(PrimeIndex).Result.PrimeNumber;
            }
                
            return View(pr);
        }
    }
}

WcfAspNetCoreService/AspNetCoreProject/Views/Prime/Index.cshtml
@model PrimeServiceReference.Primes

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <div>

        <label>Prime Index : @Html.DisplayFor(model => model.Index)</label>
        <br />
        <label>Prime Number : @Html.DisplayFor(model => model.PrimeNumber)</label>
        <br />
        <br />
</div>

    
    <form asp-controller="Prime" asp-action="GetPrimeByIndex" method="post">
        <label>Enter prime index</label>
        <input type="text" name="PrimeIndex" placeholder="Prime index..." />
        <br /><br />
        <input type='submit' name='PrimeBtn' value='Find Prime' style="width:100px;">
    </form>
</body>
</html>